# Generated by Django 5.2.4 on 2025-07-15 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('barista', '☕ Barista'), ('supervisor', '👨\u200d💼 Supervisor'), ('gerente', '🎯 Gerente'), ('aprendiz', '📚 Aprendiz')], default='barista', max_length=20)),
                ('turno', models.CharField(choices=[('manha', '🌅 Manhã (06:00 - 14:00)'), ('tarde', '☀️ Tarde (14:00 - 22:00)'), ('noite', '🌙 Noite (22:00 - 06:00)'), ('integral', '🕐 Integral')], default='manha', max_length=10)),
                ('data_contratacao', models.DateField(default=django.utils.timezone.now)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.TextField(blank=True)),
                ('especialidade', models.TextField(blank=True, help_text='Especialidades em preparo de bebidas')),
                ('pedidos_preparados', models.IntegerField(default=0)),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('tempo_medio_preparo', models.DurationField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('em_servico', models.BooleanField(default=False)),
                ('pode_gerenciar_cardapio', models.BooleanField(default=False)),
                ('pode_ver_financeiro', models.BooleanField(default=False)),
                ('pode_gerenciar_funcionarios', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Funcionário',
                'verbose_name_plural': 'Perfis dos Funcionários',
            },
        ),
        migrations.CreateModel(
            name='RegistroTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('horas_trabalhadas', models.DurationField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='cozinha.funcionarioprofile')),
            ],
            options={
                'verbose_name': 'Registro de Turno',
                'verbose_name_plural': 'Registros de Turnos',
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
