# Generated by Django 5.2.4 on 2025-07-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroTurno',
        ),
        migrations.DeleteModel(
            name='FuncionarioProfile',
        ),
    ]
