# Generated by Django 5.2.4 on 2025-07-15 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_hogwarts', models.CharField(choices=[('grifinoria', '🦁 Grifinória'), ('sonserina', '🐍 Sonserina'), ('corvinal', '🦅 Corvinal'), ('lufa_lufa', '🦡 Lufa-Lufa')], default='grifinoria', max_length=20)),
                ('pontos_fidelidade', models.IntegerField(default=0)),
                ('nivel_fidelidade', models.CharField(choices=[('bronze', 'Bronze'), ('prata', 'Prata'), ('ouro', 'Ouro')], default='bronze', max_length=10)),
                ('total_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedidos_realizados', models.IntegerField(default=0)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('preferencias_bebida', models.TextField(blank=True, help_text='Preferências e observações sobre bebidas')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Cliente',
                'verbose_name_plural': 'Perfis dos Clientes',
            },
        ),
    ]
